// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var getToday = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

var argv = Process.argv;

var command = Caml_array.get(argv, 2);

var arg = Caml_array.get(argv, 3);

console.log(command + " " + arg);

var encoding = "utf8";

exports.getToday = getToday;
exports.encoding = encoding;
exports.argv = argv;
exports.command = command;
exports.arg = arg;
/* argv Not a pure module */
