// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");

var getToday = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

var argv = Process.argv;

var args = argv.slice(2);

function isEmpty(x) {
  return x.length === 0;
}

console.log(args.length === 0);

var encoding = "utf8";

var pending_todos_file = "todo.txt";

var completed_todos_file = "done.txt";

var help_string = "Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics";

exports.getToday = getToday;
exports.encoding = encoding;
exports.pending_todos_file = pending_todos_file;
exports.completed_todos_file = completed_todos_file;
exports.help_string = help_string;
exports.argv = argv;
exports.args = args;
exports.isEmpty = isEmpty;
/* argv Not a pure module */
